version: "3"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=no-tirar
      - POSTGRES_USER=manfred
      - POSTGRES_PASSWORD=SEGa1122
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./dumps:/dumps
volumes:
  postgres-data:
