import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/Providers";
import { auth } from "@/lib/auth";
import TopBar from "@/components/molecules/TopBar";
import { inter, merriweather_sans } from "./fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${merriweather_sans.className} bg-gray-100 text-black dark:bg-stone-900 dark:text-white`}
      >
        <Providers session={session}>
          <TopBar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
};

export default Layout;
