"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/xgo6IPwH3dr
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from "@/components/ui/card";
import { ResponsiveLine, Serie } from "@nivo/line";

interface FilledTimeseriesChartProps {
  className?: string;
}

const data: Serie[] = [
  {
    id: "Desktop",
    data: [
      { x: "Jan", y: 43 },
      { x: "Feb", y: 137 },
      { x: "Mar", y: 61 },
      { x: "Apr", y: 145 },
      { x: "May", y: 26 },
      { x: "Jun", y: 154 },
    ],
  },
];

export const CurvedChart = () => {
  return (
    <Card className="w-full max-w-3xl">
      <CardHeader>
        <div className="flex gap-6">
          <div>
            <div className="text-sm text-gray-500">Pedidos</div>
            <div className="text-2xl font-bold">45</div>
          </div>
          <div>
            <div className="text-sm text-gray-500">Ventas</div>
            <div className="text-2xl font-bold">$ 225.599</div>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <FilledTimeseriesChart className="aspect-[16/9] w-full" />
      </CardContent>
    </Card>
  );
};

const FilledTimeseriesChart = (props: FilledTimeseriesChartProps) => {
  return (
    <div {...props}>
      <ResponsiveLine
        data={data}
        margin={{ top: 10, right: 40, bottom: 40, left: 10 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        axisTop={null}
        axisRight={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={null}
        colors={["#22c55e"]}
        pointSize={6}
        useMesh={true}
        curve="monotoneX"
        enableArea={true}
        gridXValues={[1, 2, 3, 4, 5, 6]}
        gridYValues={[]}
        defs={[
          {
            id: "line-chart-gradient",
            type: "linearGradient",
            colors: [
              { offset: 0, color: "#22c55e" },
              { offset: 100, color: "#22c55e", opacity: 0.3 },
            ],
          },
        ]}
        fill={[{ match: "*", id: "line-chart-gradient" }]}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
        }}
        role="application"
      />
    </div>
  );
};
